version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'monthly'
          day: tuesday
          time: '00:00'
      open-pull-requests-limit: 3
      target-branch: 'development'
      commit-message:
          prefix: 'github-action'
      labels:
          - dependabot

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
          day: monday
          time: '00:00'
      open-pull-requests-limit: 3
      target-branch: 'development'
      commit-message:
          prefix: 'deps'
      labels:
          - dependabot
          - dependencies
      versioning-strategy: increase
