version: '3.8'
services:
  mongodb-primary:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    restart: unless-stopped
    volumes:
      - mongodb_master_data:/bitnami
    networks:
      - app-network
    ports: 
      - 27021:27017

  mongodb-secondary:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-secondary
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: password123
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    restart: unless-stopped
    networks:
      - app-network
    ports: 
      - 27022:27017

  mongodb-arbiter:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-arbiter
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: password123
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    restart: unless-stopped
    networks:
      - app-network
    ports: 
      - 27023:27017

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mongodb_master_data:
    driver: local
