name: CI
on:
  push:
    branches: 
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit
        id: prepare
        run: echo "::set-output name=github_short_sha::$(git rev-parse --short HEAD)"

      - name: Get latest version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Version
        run: |
          echo New version is: ${{ steps.package-version.outputs.current-version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/setup-buildx-action@v1
        id: builder

      - uses: docker/setup-buildx-action@v1
        id: main

      - name: Builder name
        run: echo ${{ steps.builder.outputs.name }}

      - name: Main builder name
        run: echo ${{ steps.main.outputs.name }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build against builder
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: ./prod/dockerfile
          target: builder

      - name: Build against main and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.main.outputs.name }}
          dockerfile: ./prod/dockerfile
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/ack-nestjs-boilerplate-mongoose
          target: main
          tags: |
            latest
            ${{ steps.last_release.outputs.tag_name }}
            ${{ steps.last_release.outputs.tag_name }}_sha-${{ steps.prepare.outputs.github_short_sha }}
          push: true



