name: CI
on:
  push:
    branches: 
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ack-nestjs-boilerplate-mongoose
      DOCKERFILE: ./prod/docker
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Get commit and git branch name
        id: git
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch_name::${GITHUB_REF##*/}"
      
      - name: Get latest version
        id: version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Git
        run: |
          echo Branch name is: ${{ steps.git.outputs.current-version}}
          echo Short sha: ${{ steps.git.outputs.branch_name}}
          echo Version is: ${{ steps.version.outputs.current-version}}

      - name: Environment
        run: |
          echo APP_NAME is: ${{ env.APP_NAME}}
          echo DOCKERFILE is: ${{ env.DOCKERFILE}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/setup-buildx-action@v1
        id: builder

      - uses: docker/setup-buildx-action@v1
        id: main

      - name: Builder name
        run: echo ${{ steps.builder.outputs.name }}

      - name: Main builder name
        run: echo ${{ steps.main.outputs.name }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build against builder
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: ./prod/dockerfile
          target: builder

      - name: Build against main and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.main.outputs.name }}
          dockerfile: ${{ env.DOCKERFILE }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
          target: ${{ steps.git.outputs.branch_name}}
          tags: |
            latest
            v${{ steps.version.outputs.current-version}}
            v${{ steps.version.outputs.current-version}}_sha-${{ steps.git.outputs.short_sha }}
          push: true



